config/routes.rb
Rails.application.routes.draw do
  resources :courses, :students do
    resources :classrooms
  end
  

  root 'welcome#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :course
	belongs_to :student

	before_save :update_student_status
	after_destroy :update_student_status

	validates_uniqueness_of :student_id, scope: :course_id

	private 
		def update_student_status
			@enrolled = false
			self.student.courses.each do |course|
				if course.enrolling? || course.ongoing?
					@enrolled = true
				end
			end

			@enrolled ? self.student.status = Student.statuses[:enrolled] : self.student.status = Student.statuses[:idle]
			self.student.save
		end		
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :classrooms, dependent: :destroy
	has_many :students, through: :classrooms

	accepts_nested_attributes_for :classrooms, :students

	enum status: [ :enrolling, :ongoing, :closed ]
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :status, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :classrooms, dependent: :destroy
	has_many :courses, through: :classrooms

	accepts_nested_attributes_for :classrooms, :courses

	before_create :generate_register_number
	before_save :update_status

	enum status: [ :idle, :enrolled ]
	validates :name, presence: true	
	validates :register_number, uniqueness: true

	private
		def generate_register_number			
			self.register_number = rand.to_s[2..11]
		end

		def update_status
			@enrolled = false
			self.courses.each do |course|
				if course.enrolling? || course.ongoing?
					@enrolled = true
				end
			end

			@enrolled ? self.status = Student.statuses[:enrolled] : self.status = Student.statuses[:idle]
		end		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end

	def show
		@course = Course.find(params[:id])
	end

	def new
		@course = Course.new
		@statuses = Course.statuses
	end

	def create		
		@course = Course.new(course_params)
		@statuses = Course.statuses
		if @course.save
			redirect_to @course
		else
			render 'new'
		end
	end

	def edit
		@course = Course.find(params[:id])
		@statuses = Course.statuses
	end

	def update
		@course = Course.find(params[:id])
		@statuses = Course.statuses

		if @course.update(course_params)			
			redirect_to @course
		else
			render 'edit'
		end
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy

		redirect_to courses_path
	end

	private 
		def course_params
			params.require(:course).permit(:name, :description, :status, :student_ids => [])
		end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students = Student.all
	end

	def show
		@student = Student.find(params[:id])
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)

		if @student.save
			redirect_to @student
		else
			render 'new'
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])

		# Avoids deleting ongoing and closed courses, which are not shown in the selection.
		# There must be a better way to do this...		
		@student.classrooms.each do |classroom|
			if classroom.course.ongoing? || classroom.course.closed?
				params[:student][:course_ids].push(classroom.course_id)
			end
		end		

		if @student.update(student_params)			
			redirect_to @student
		else
			render 'edit'
		end
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy

		redirect_to students_path
	end

	private 
		def student_params
			params.require(:student).permit(:name, :course_ids => [])
		end	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@courses = Course.where("status = ?", Course.statuses[:enrolling])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
<% if @course.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>
	<ul>
	<% @course.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
</div>
<% end %>
<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</p>

<p>
	<%= f.label :description %><br>
	<%= f.text_area :description %>
</p>

<p>
	<%= f.label :status %>
    <%= f.select :status, options_for_select(@statuses.collect { |s| [s[0].humanize, s[0]] }, selected: @course.status), {} , class: "form-control" %>
</p>

<% if @course.enrolling? || @course.ongoing? || @course.present? && !@course.closed? %>
<p>
	<%= f.label :student_ids, 'Students' %><br>
	<%= f.select :student_ids, Student.all.collect {|s| [s.name, s.id]}, {}, :multiple => true %>
</p>
<% end %>

<p>
	<%= f.submit %>
</p>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<%= link_to 'New course', new_course_path %>

<% if @courses.any? %>
<table>
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Status</th>
		<th colspan="2"></th>
	</tr>
<% @courses.each do |course| %>
	<tr>
		<td><%= course.name %></td>
		<td><%= course.description %></td>
		<td><%= course.status.humanize %></td>
		<td><%= link_to 'Show', course_path(course) %></td>
		<td><%= link_to 'Edit', edit_course_path(course) %></td>
		<td><%= link_to 'Destroy', course_path(course), 
			method: :delete, data: {confirm: 'Are you sure?' } %></td>
	</tr>
<% end %>
</table>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @course.name %>
</p>

<p>
	<strong>Description:</strong>
	<%= @course.description %>
</p>

<p>
	<strong>Status:</strong>
	<%= @course.status.humanize %>
</p>

<% if @course.students.any? %>
<h2>Students</h2>
<table>
	<tr>
		<th>Name</th>
		<th>Register Number</th>
		<th>Entry at</th>
		<th colspan="2"></th>
	</tr>
	<% @course.classrooms.each do |classroom| %>
	<tr>
		<td><%= classroom.student.name %></td>
		<td><%= classroom.student.register_number %></td>
		<td><%= classroom.created_at %></td>
		<td><%= link_to 'Show', student_path(classroom.student) %></td>
	</tr>
	<% end %>
</table>
<% end %>

<%= link_to 'Back', courses_path %>
| <%= link_to 'Edit', edit_course_path(@course) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', controller: 'welcome' %>
<%= link_to 'Courses', controller: 'courses' %>
<%= link_to 'Students', controller: 'students' %>
<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
<% if @student.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
	<ul>
	<% @student.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
</div>
<% end %>
<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</p>

<p>
	<%= f.label :course_ids, 'Enrolling courses' %><br>
	<%= f.select :course_ids, Course.where("status = ?", Course.statuses[:enrolling]).collect {|c| [c.name, c.id]}, {}, :multiple => true %>
</p>

<p>
	<%= f.submit %>
</p>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<%= link_to 'New student', new_student_path %>

<% if @students.any? %>
<table>
	<tr>
		<th>Name</th>
		<th>Register Number</th>
		<th>Status</th>
		<th colspan="2"></th>
	</tr>
<% @students.each do |student| %>
	<tr>
		<td><%= student.name %></td>
		<td><%= student.register_number %></td>
		<td><%= student.status.humanize %></td>
		<td><%= link_to 'Show', student_path(student) %></td>
		<td><%= link_to 'Edit', edit_student_path(student) %></td>
		<td><%= link_to 'Destroy', student_path(student), 
			method: :delete, data: {confirm: 'Are you sure?' } %></td>
	</tr>
<% end %>
</table>
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @student.name %>
</p>

<p>
	<strong>Register Number:</strong>
	<%= @student.register_number %>
</p>

<p>
	<strong>Status:</strong>
	<%= @student.status.humanize %>
</p>

<% if @student.courses.any? %>
<h2>Courses</h2>
<table>
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Status</th>
		<th>Entry at</th>
		<th colspan="2"></th>
	</tr>
	<% @student.courses.each do |course| %>
	<tr>
		<td><%= course.name %></td>
		<td><%= course.description %></td>
		<td><%= course.status.humanize %></td>
		<td><%= course.classrooms.find_by(student: @student).created_at %>
		<td><%= link_to 'Show', course_path(course) %></td>
	</tr>
	<% end %>
</table>
<% end %>

<%= link_to 'Back', students_path %>
| <%= link_to 'Edit', edit_student_path(@student) %>

app/views/welcome/index.html.erb
<h1>Welcome to Rails Courses!</h1>

<p>Here you will find the best Rail Courses for free!<p>

<p>New here? <%= link_to 'sign up', controller: 'students', action: 'new' %> now and enroll to any of the courses below!</p>

<h2>Enrolling now</h2>
<% if @courses.any? %>
<table>
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th colspan="2"></th>
	</tr>
	<% @courses.each do |course| %>
	<tr>
		<td><%= course.name %></td>
		<td><%= course.description %></td>
	</tr>
	<% end %>
</table>
<% else %>
<p>Uhhh... actually there is no course to be enrolled! Sorry for the inconvenience.</p>
<% end %>

<p>You can also checkout the <%= link_to 'courses area', controller: 'courses' %> to see the ongoing courses, as well as other courses that were already given and may be opened again soon!</p>

<p>If you are looking for someone, be sure to see the <%= link_to 'students area', controller: 'students' %>, where all of our students are registred. </p>

<p>Enjoy Ruby On Rails, the greatest open-source web framework ever!!!</p>